language: node_js

node_js:
  - 10
  - lts/*
  - node

install:
  - bash build/travis_install

script:
  - npm run build:all
  - npm run test:all
  - npm run lint:all

after_script:
  - bash build/coveralls
