service:
  # address: listening address for the http/https protocoll
  address: 'localhost'
  http:
    # port: for the http protocol; default 80
    port: 8080
    # maxHeaderSize: the maximum length of request headers in bytes; default 8192
    maxHeaderSize: 8192
    # disabled: set to 'true' if you want to disable http; default is 'false'
    disabled: 'false'
    # redirect: set to 'false' if you do not want to redirect to https; default is 'true'
    redirect: true
    # redirectCode: the status code for redirecting; default 307
    redirectCode: 307
    # redirectLocaltion: the locate to redirect to
    # redirectLocation: https://localhost:443
  https:
    # port: for the https protocol; default 443
    port: 8443
    # key: private key file in PEM format (absolute or relative to this config directory)
    key: './secrets/ceritifcates/key.pem'
    # cert: cert chain file in PEM format (absolute or relative to this config directory)
    cert: './secrets/ceritifcates/cert.pem'
    # maxHeaderSize: the maximum length of request headers in bytes; default 8192
    maxHeaderSize: 8192
    # disabled: set to 'true' if you want to disable https; default is 'false'
    disabled: 'false'
  limits:
    # jsonBody: maximum json body size; default 10kb
    jsonBody: '10kb'

  # trustProxy: ip addresses of trusted proxies delimited by ','
  #   please see 'IP addresses' in https://expressjs.com/en/guide/behind-proxies.html
  trustProxy: '127.0.0.1'

  throttle:
    # ttl: the time to live in seconds; default 60
    ttl: 60
    # limit: number of hits allowed before returning http status 429; default 10
    limit: 10

  session:
    # secret: the secret for signing the session cookie, optional following additional key delimited by ',' for verifying
    # please set your own!!!
    secret: h0m30fTh1ngs
    # name: the name of the session cookie; default 'sessionId'
    name: sessionId
    # maxAge: Specifies the number (in milliseconds) to use when calculating the Expires Set-Cookie attribute.
    # the cookie will expire in maxAge since the last response was sent
    # default: 900000 (15 * 60 * 1000): 15 min
    maxAge: 900000

  logging:
    console:
      # level: 'silly', 'debug', 'verbose', 'help', 'info' (default), 'warn', 'error'
      level: 'help'
      # silent: set to 'true' to turn of logging; default is 'false'
      # silent: true
    file:
      # level: 'silly', 'debug', 'verbose', 'help', 'info', 'warn' (default), 'error'
      level: 'warn'
      # path to the logfile (absolute or relative to this config directory)
      path: 'var/log/gateway.log'
      # silent: set to 'true' to turn of logging; default is 'false'
      silent: true

cli:
  logging:
  console:
    # level: 'silly', 'debug', 'verbose', 'help', 'info' (default), 'warn', 'error'
    level: 'help'
    # silent: set to 'true' to turn of logging; default is 'false'
    # silent: true
  file:
    # level: 'silly', 'debug', 'verbose', 'help', 'info', 'warn' (default), 'error'
    level: 'warn'
    # path to the logfile (absolute or relative to this config directory)
    path: 'var/log/gateway.log'
    # silent: set to 'true' to turn of logging; default is 'false'
    silent: true
