logging:
  console:
    level: 'debug'
  file:
    path: 'var/log/gateway.log'
    silent: true

service:
  http:
    port: 8080
    address: 'localhost'
    disabled: 'false'
  https:
    port: 8443
    address: 'localhost'
    key: './secrets/private-key.pem'
    cert: './secrets/public-certificate.pem'
    disabled: 'false'
