name: Build Workflow
"on":
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - 16.x
    steps:
      - name: "Set up Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - uses: actions/checkout@v2
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Run"
        run: "npm run ci"
      - name: Upload nestjs-utils coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/projects/node/libs/nestjs-utils
          flags: "nestjs-utils"
          fail_ci_if_error: true
          verbose: true
      - name: Upload nestjs-config coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/projects/node/libs/nestjs-config
          flags: "nestjs-config"
          fail_ci_if_error: true
          verbose: true
      - name: Upload nestjs-logger coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/projects/node/libs/nestjs-logger
          flags: "nestjs-logger"
          fail_ci_if_error: true
          verbose: true
      - name: Upload nestjs-sqlite3 coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/projects/node/libs/nestjs-sqlite3
          flags: "nestjs-sqlite3"
          fail_ci_if_error: true
          verbose: true
